/* Generated by Yosys 0.64 (git sha1 8449dd470, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) [the-openroad-project/yosys] */

module Sync_FIFO(clk, rst, wr_en, rd_en, full, empty, din, dout);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input wr_en;
  wire wr_en;
  input rd_en;
  wire rd_en;
  output full;
  wire full;
  output empty;
  wire empty;
  input [7:0] din;
  wire [7:0] din;
  output [7:0] dout;
  wire [7:0] dout;
  wire _0_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _10_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _11_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _12_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _13_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _14_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _15_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _16_;
  wire [7:0] _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _1_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _2_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _3_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  wire _46_;
  wire _47_;
  wire _48_;
  wire _49_;
  wire _4_;
  wire _50_;
  wire _51_;
  wire _52_;
  wire _53_;
  wire _54_;
  wire _55_;
  wire _56_;
  wire _57_;
  wire _58_;
  wire _59_;
  wire _5_;
  wire _60_;
  wire _61_;
  wire _62_;
  wire _63_;
  wire _64_;
  wire _65_;
  wire _66_;
  wire _67_;
  wire _68_;
  wire _69_;
  wire _6_;
  wire _70_;
  wire _71_;
  wire _72_;
  wire _73_;
  wire _74_;
  wire _75_;
  wire _76_;
  wire _77_;
  wire _78_;
  wire _79_;
  wire _7_;
  wire _80_;
  wire _81_;
  wire _82_;
  wire _83_;
  wire _84_;
  wire _85_;
  wire _86_;
  wire _87_;
  wire _88_;
  wire _89_;
  wire _8_;
  wire _90_;
  wire _91_;
  wire _92_;
  wire _93_;
  wire _94_;
  wire _95_;
  wire _96_;
  wire _97_;
  wire _98_;
  wire _99_;
  wire _9_;
  wire [7:0] \mem[0] ;
  wire [7:0] \mem[10] ;
  wire [7:0] \mem[11] ;
  wire [7:0] \mem[12] ;
  wire [7:0] \mem[13] ;
  wire [7:0] \mem[14] ;
  wire [7:0] \mem[15] ;
  wire [7:0] \mem[1] ;
  wire [7:0] \mem[2] ;
  wire [7:0] \mem[3] ;
  wire [7:0] \mem[4] ;
  wire [7:0] \mem[5] ;
  wire [7:0] \mem[6] ;
  wire [7:0] \mem[7] ;
  wire [7:0] \mem[8] ;
  wire [7:0] \mem[9] ;
  wire [4:0] rd_ptr;
  wire [4:0] wr_ptr;
  sky130_fd_sc_hd__clkinv_1 _180_ (
    .A(rd_ptr[4]),
    .Y(_92_)
  );
  sky130_fd_sc_hd__clkinv_1 _181_ (
    .A(wr_ptr[2]),
    .Y(_93_)
  );
  sky130_fd_sc_hd__clkinv_1 _182_ (
    .A(wr_ptr[3]),
    .Y(_94_)
  );
  sky130_fd_sc_hd__clkinv_1 _183_ (
    .A(rd_ptr[2]),
    .Y(_95_)
  );
  sky130_fd_sc_hd__xor2_1 _184_ (
    .A(wr_ptr[0]),
    .B(rd_ptr[0]),
    .X(_96_)
  );
  sky130_fd_sc_hd__xor2_1 _185_ (
    .A(wr_ptr[2]),
    .B(rd_ptr[2]),
    .X(_97_)
  );
  sky130_fd_sc_hd__nor2_1 _186_ (
    .A(_96_),
    .B(_97_),
    .Y(_98_)
  );
  sky130_fd_sc_hd__xor2_1 _187_ (
    .A(wr_ptr[1]),
    .B(rd_ptr[1]),
    .X(_99_)
  );
  sky130_fd_sc_hd__xnor2_1 _188_ (
    .A(wr_ptr[3]),
    .B(rd_ptr[3]),
    .Y(_100_)
  );
  sky130_fd_sc_hd__or4b_1 _189_ (
    .A(_96_),
    .B(_97_),
    .C(_99_),
    .D_N(_100_),
    .X(_101_)
  );
  sky130_fd_sc_hd__xnor2_1 _190_ (
    .A(rd_ptr[4]),
    .B(wr_ptr[4]),
    .Y(_102_)
  );
  sky130_fd_sc_hd__xor2_1 _191_ (
    .A(rd_ptr[4]),
    .B(wr_ptr[4]),
    .X(_103_)
  );
  sky130_fd_sc_hd__nor2_1 _192_ (
    .A(_101_),
    .B(_102_),
    .Y(full)
  );
  sky130_fd_sc_hd__o21a_1 _193_ (
    .A1(_101_),
    .A2(_102_),
    .B1(wr_en),
    .X(_104_)
  );
  sky130_fd_sc_hd__o211a_1 _194_ (
    .A1(_101_),
    .A2(_102_),
    .B1(rst),
    .C1(wr_en),
    .X(_105_)
  );
  sky130_fd_sc_hd__nand2_1 _195_ (
    .A(rst),
    .B(_104_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__and2_0 _196_ (
    .A(din[6]),
    .B(_105_),
    .X(_170_[6])
  );
  sky130_fd_sc_hd__and2_0 _197_ (
    .A(din[5]),
    .B(_105_),
    .X(_170_[5])
  );
  sky130_fd_sc_hd__and2_0 _198_ (
    .A(din[4]),
    .B(_105_),
    .X(_170_[4])
  );
  sky130_fd_sc_hd__and2_0 _199_ (
    .A(din[3]),
    .B(_105_),
    .X(_170_[3])
  );
  sky130_fd_sc_hd__and2_0 _200_ (
    .A(din[2]),
    .B(_105_),
    .X(_170_[2])
  );
  sky130_fd_sc_hd__and2_0 _201_ (
    .A(din[1]),
    .B(_105_),
    .X(_170_[1])
  );
  sky130_fd_sc_hd__and2_0 _202_ (
    .A(din[0]),
    .B(_105_),
    .X(_170_[0])
  );
  sky130_fd_sc_hd__nor2_1 _203_ (
    .A(_101_),
    .B(_103_),
    .Y(empty)
  );
  sky130_fd_sc_hd__o21a_1 _204_ (
    .A1(_101_),
    .A2(_103_),
    .B1(rd_en),
    .X(_107_)
  );
  sky130_fd_sc_hd__o2111ai_1 _205_ (
    .A1(_101_),
    .A2(_102_),
    .B1(wr_ptr[1]),
    .C1(rst),
    .D1(wr_en),
    .Y(_108_)
  );
  sky130_fd_sc_hd__nand3_1 _206_ (
    .A(_98_),
    .B(_100_),
    .C(_105_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__xnor2_1 _207_ (
    .A(rd_ptr[1]),
    .B(_108_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__mux2i_1 _208_ (
    .A0(\mem[8] [6]),
    .A1(\mem[9] [6]),
    .S(rd_ptr[0]),
    .Y(_111_)
  );
  sky130_fd_sc_hd__nor2_1 _209_ (
    .A(rd_ptr[1]),
    .B(_111_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _210_ (
    .A(rd_ptr[1]),
    .SLEEP(rd_ptr[0]),
    .X(_113_)
  );
  sky130_fd_sc_hd__and2_0 _211_ (
    .A(rd_ptr[0]),
    .B(rd_ptr[1]),
    .X(_114_)
  );
  sky130_fd_sc_hd__a221oi_1 _212_ (
    .A1(\mem[10] [6]),
    .A2(_113_),
    .B1(_114_),
    .B2(\mem[11] [6]),
    .C1(_112_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__mux4_2 _213_ (
    .A0(\mem[12] [6]),
    .A1(\mem[13] [6]),
    .A2(\mem[14] [6]),
    .A3(\mem[15] [6]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[1]),
    .X(_116_)
  );
  sky130_fd_sc_hd__nand2_1 _214_ (
    .A(rd_ptr[2]),
    .B(_116_),
    .Y(_117_)
  );
  sky130_fd_sc_hd__mux2i_1 _215_ (
    .A0(\mem[4] [6]),
    .A1(\mem[5] [6]),
    .S(rd_ptr[0]),
    .Y(_118_)
  );
  sky130_fd_sc_hd__nor2_1 _216_ (
    .A(rd_ptr[1]),
    .B(_118_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__a221oi_1 _217_ (
    .A1(\mem[6] [6]),
    .A2(_113_),
    .B1(_114_),
    .B2(\mem[7] [6]),
    .C1(_119_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__mux4_2 _218_ (
    .A0(\mem[0] [6]),
    .A1(\mem[1] [6]),
    .A2(\mem[2] [6]),
    .A3(\mem[3] [6]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[1]),
    .X(_121_)
  );
  sky130_fd_sc_hd__o211ai_1 _219_ (
    .A1(rd_ptr[2]),
    .A2(_115_),
    .B1(_117_),
    .C1(rd_ptr[3]),
    .Y(_122_)
  );
  sky130_fd_sc_hd__a21oi_1 _220_ (
    .A1(_95_),
    .A2(_121_),
    .B1(rd_ptr[3]),
    .Y(_123_)
  );
  sky130_fd_sc_hd__o21ai_0 _221_ (
    .A1(_95_),
    .A2(_120_),
    .B1(_123_),
    .Y(_124_)
  );
  sky130_fd_sc_hd__o211ai_1 _222_ (
    .A1(_109_),
    .A2(_110_),
    .B1(_122_),
    .C1(_124_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__o21ai_0 _223_ (
    .A1(dout[6]),
    .A2(_107_),
    .B1(rst),
    .Y(_126_)
  );
  sky130_fd_sc_hd__a21oi_1 _224_ (
    .A1(_107_),
    .A2(_125_),
    .B1(_126_),
    .Y(_88_)
  );
  sky130_fd_sc_hd__mux2i_1 _225_ (
    .A0(\mem[0] [5]),
    .A1(\mem[1] [5]),
    .S(rd_ptr[0]),
    .Y(_127_)
  );
  sky130_fd_sc_hd__a221oi_1 _226_ (
    .A1(\mem[2] [5]),
    .A2(_113_),
    .B1(_114_),
    .B2(\mem[3] [5]),
    .C1(rd_ptr[2]),
    .Y(_128_)
  );
  sky130_fd_sc_hd__o21ai_0 _227_ (
    .A1(rd_ptr[1]),
    .A2(_127_),
    .B1(_128_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__mux2i_1 _228_ (
    .A0(\mem[4] [5]),
    .A1(\mem[5] [5]),
    .S(rd_ptr[0]),
    .Y(_130_)
  );
  sky130_fd_sc_hd__a221oi_1 _229_ (
    .A1(\mem[6] [5]),
    .A2(_113_),
    .B1(_114_),
    .B2(\mem[7] [5]),
    .C1(_95_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__o21ai_0 _230_ (
    .A1(rd_ptr[1]),
    .A2(_130_),
    .B1(_131_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__mux2i_1 _231_ (
    .A0(\mem[12] [5]),
    .A1(\mem[13] [5]),
    .S(rd_ptr[0]),
    .Y(_133_)
  );
  sky130_fd_sc_hd__a221oi_1 _232_ (
    .A1(\mem[14] [5]),
    .A2(_113_),
    .B1(_114_),
    .B2(\mem[15] [5]),
    .C1(_95_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__o21a_1 _233_ (
    .A1(rd_ptr[1]),
    .A2(_133_),
    .B1(_134_),
    .X(_135_)
  );
  sky130_fd_sc_hd__mux2i_1 _234_ (
    .A0(\mem[8] [5]),
    .A1(\mem[9] [5]),
    .S(rd_ptr[0]),
    .Y(_136_)
  );
  sky130_fd_sc_hd__a221oi_1 _235_ (
    .A1(\mem[10] [5]),
    .A2(_113_),
    .B1(_114_),
    .B2(\mem[11] [5]),
    .C1(rd_ptr[2]),
    .Y(_137_)
  );
  sky130_fd_sc_hd__o21a_1 _236_ (
    .A1(rd_ptr[1]),
    .A2(_136_),
    .B1(_137_),
    .X(_138_)
  );
  sky130_fd_sc_hd__o21ai_0 _237_ (
    .A1(_135_),
    .A2(_138_),
    .B1(rd_ptr[3]),
    .Y(_139_)
  );
  sky130_fd_sc_hd__a21o_1 _238_ (
    .A1(_129_),
    .A2(_132_),
    .B1(rd_ptr[3]),
    .X(_140_)
  );
  sky130_fd_sc_hd__o211ai_1 _239_ (
    .A1(_109_),
    .A2(_110_),
    .B1(_139_),
    .C1(_140_),
    .Y(_141_)
  );
  sky130_fd_sc_hd__o21ai_0 _240_ (
    .A1(dout[5]),
    .A2(_107_),
    .B1(rst),
    .Y(_142_)
  );
  sky130_fd_sc_hd__a21oi_1 _241_ (
    .A1(_107_),
    .A2(_141_),
    .B1(_142_),
    .Y(_90_)
  );
  sky130_fd_sc_hd__mux2i_1 _242_ (
    .A0(\mem[4] [4]),
    .A1(\mem[5] [4]),
    .S(rd_ptr[0]),
    .Y(_143_)
  );
  sky130_fd_sc_hd__a221oi_1 _243_ (
    .A1(\mem[6] [4]),
    .A2(_113_),
    .B1(_114_),
    .B2(\mem[7] [4]),
    .C1(_95_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__o21ai_0 _244_ (
    .A1(rd_ptr[1]),
    .A2(_143_),
    .B1(_144_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__mux2i_1 _245_ (
    .A0(\mem[0] [4]),
    .A1(\mem[1] [4]),
    .S(rd_ptr[0]),
    .Y(_146_)
  );
  sky130_fd_sc_hd__a221oi_1 _246_ (
    .A1(\mem[2] [4]),
    .A2(_113_),
    .B1(_114_),
    .B2(\mem[3] [4]),
    .C1(rd_ptr[2]),
    .Y(_147_)
  );
  sky130_fd_sc_hd__o21ai_0 _247_ (
    .A1(rd_ptr[1]),
    .A2(_146_),
    .B1(_147_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__mux2i_1 _248_ (
    .A0(\mem[8] [4]),
    .A1(\mem[9] [4]),
    .S(rd_ptr[0]),
    .Y(_149_)
  );
  sky130_fd_sc_hd__a31oi_1 _249_ (
    .A1(rd_ptr[0]),
    .A2(rd_ptr[1]),
    .A3(\mem[11] [4]),
    .B1(rd_ptr[2]),
    .Y(_150_)
  );
  sky130_fd_sc_hd__o21ai_0 _250_ (
    .A1(rd_ptr[1]),
    .A2(_149_),
    .B1(_150_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__a21oi_1 _251_ (
    .A1(\mem[10] [4]),
    .A2(_113_),
    .B1(_151_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__mux2i_1 _252_ (
    .A0(\mem[12] [4]),
    .A1(\mem[13] [4]),
    .S(rd_ptr[0]),
    .Y(_153_)
  );
  sky130_fd_sc_hd__a221oi_1 _253_ (
    .A1(\mem[14] [4]),
    .A2(_113_),
    .B1(_114_),
    .B2(\mem[15] [4]),
    .C1(_95_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__o21a_1 _254_ (
    .A1(rd_ptr[1]),
    .A2(_153_),
    .B1(_154_),
    .X(_155_)
  );
  sky130_fd_sc_hd__o21ai_0 _255_ (
    .A1(_152_),
    .A2(_155_),
    .B1(rd_ptr[3]),
    .Y(_156_)
  );
  sky130_fd_sc_hd__a21o_1 _256_ (
    .A1(_145_),
    .A2(_148_),
    .B1(rd_ptr[3]),
    .X(_157_)
  );
  sky130_fd_sc_hd__o211ai_1 _257_ (
    .A1(_109_),
    .A2(_110_),
    .B1(_156_),
    .C1(_157_),
    .Y(_158_)
  );
  sky130_fd_sc_hd__o21ai_0 _258_ (
    .A1(dout[4]),
    .A2(_107_),
    .B1(rst),
    .Y(_159_)
  );
  sky130_fd_sc_hd__a21oi_1 _259_ (
    .A1(_107_),
    .A2(_158_),
    .B1(_159_),
    .Y(_91_)
  );
  sky130_fd_sc_hd__mux4_2 _260_ (
    .A0(\mem[4] [3]),
    .A1(\mem[5] [3]),
    .A2(\mem[6] [3]),
    .A3(\mem[7] [3]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[1]),
    .X(_160_)
  );
  sky130_fd_sc_hd__mux4_2 _261_ (
    .A0(\mem[12] [3]),
    .A1(\mem[13] [3]),
    .A2(\mem[14] [3]),
    .A3(\mem[15] [3]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[1]),
    .X(_161_)
  );
  sky130_fd_sc_hd__mux4_2 _262_ (
    .A0(\mem[8] [3]),
    .A1(\mem[9] [3]),
    .A2(\mem[10] [3]),
    .A3(\mem[11] [3]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[1]),
    .X(_162_)
  );
  sky130_fd_sc_hd__mux4_2 _263_ (
    .A0(\mem[0] [3]),
    .A1(\mem[1] [3]),
    .A2(\mem[2] [3]),
    .A3(\mem[3] [3]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[1]),
    .X(_163_)
  );
  sky130_fd_sc_hd__mux4_2 _264_ (
    .A0(_160_),
    .A1(_161_),
    .A2(_163_),
    .A3(_162_),
    .S0(rd_ptr[3]),
    .S1(_95_),
    .X(_164_)
  );
  sky130_fd_sc_hd__o21ai_0 _265_ (
    .A1(_109_),
    .A2(_110_),
    .B1(_164_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__o21ai_0 _266_ (
    .A1(dout[3]),
    .A2(_107_),
    .B1(rst),
    .Y(_166_)
  );
  sky130_fd_sc_hd__a21oi_1 _267_ (
    .A1(_107_),
    .A2(_165_),
    .B1(_166_),
    .Y(_58_)
  );
  sky130_fd_sc_hd__mux4_2 _268_ (
    .A0(\mem[12] [2]),
    .A1(\mem[13] [2]),
    .A2(\mem[14] [2]),
    .A3(\mem[15] [2]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[1]),
    .X(_167_)
  );
  sky130_fd_sc_hd__mux4_2 _269_ (
    .A0(\mem[4] [2]),
    .A1(\mem[5] [2]),
    .A2(\mem[6] [2]),
    .A3(\mem[7] [2]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[1]),
    .X(_168_)
  );
  sky130_fd_sc_hd__mux4_2 _270_ (
    .A0(\mem[8] [2]),
    .A1(\mem[9] [2]),
    .A2(\mem[10] [2]),
    .A3(\mem[11] [2]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[1]),
    .X(_169_)
  );
  sky130_fd_sc_hd__mux4_2 _271_ (
    .A0(\mem[0] [2]),
    .A1(\mem[1] [2]),
    .A2(\mem[2] [2]),
    .A3(\mem[3] [2]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[1]),
    .X(_171_)
  );
  sky130_fd_sc_hd__mux4_2 _272_ (
    .A0(_168_),
    .A1(_171_),
    .A2(_167_),
    .A3(_169_),
    .S0(_95_),
    .S1(rd_ptr[3]),
    .X(_172_)
  );
  sky130_fd_sc_hd__o21ai_0 _273_ (
    .A1(_109_),
    .A2(_110_),
    .B1(_172_),
    .Y(_173_)
  );
  sky130_fd_sc_hd__o21ai_0 _274_ (
    .A1(dout[2]),
    .A2(_107_),
    .B1(rst),
    .Y(_174_)
  );
  sky130_fd_sc_hd__a21oi_1 _275_ (
    .A1(_107_),
    .A2(_173_),
    .B1(_174_),
    .Y(_59_)
  );
  sky130_fd_sc_hd__mux4_2 _276_ (
    .A0(\mem[12] [1]),
    .A1(\mem[13] [1]),
    .A2(\mem[14] [1]),
    .A3(\mem[15] [1]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[1]),
    .X(_175_)
  );
  sky130_fd_sc_hd__mux4_2 _277_ (
    .A0(\mem[4] [1]),
    .A1(\mem[5] [1]),
    .A2(\mem[6] [1]),
    .A3(\mem[7] [1]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[1]),
    .X(_176_)
  );
  sky130_fd_sc_hd__mux4_2 _278_ (
    .A0(\mem[8] [1]),
    .A1(\mem[9] [1]),
    .A2(\mem[10] [1]),
    .A3(\mem[11] [1]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[1]),
    .X(_177_)
  );
  sky130_fd_sc_hd__mux4_2 _279_ (
    .A0(\mem[0] [1]),
    .A1(\mem[1] [1]),
    .A2(\mem[2] [1]),
    .A3(\mem[3] [1]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[1]),
    .X(_178_)
  );
  sky130_fd_sc_hd__mux4_2 _280_ (
    .A0(_176_),
    .A1(_178_),
    .A2(_175_),
    .A3(_177_),
    .S0(_95_),
    .S1(rd_ptr[3]),
    .X(_179_)
  );
  sky130_fd_sc_hd__o21ai_0 _281_ (
    .A1(_109_),
    .A2(_110_),
    .B1(_179_),
    .Y(_0_)
  );
  sky130_fd_sc_hd__o21ai_0 _282_ (
    .A1(dout[1]),
    .A2(_107_),
    .B1(rst),
    .Y(_1_)
  );
  sky130_fd_sc_hd__a21oi_1 _283_ (
    .A1(_107_),
    .A2(_0_),
    .B1(_1_),
    .Y(_60_)
  );
  sky130_fd_sc_hd__mux2i_1 _284_ (
    .A0(\mem[12] [0]),
    .A1(\mem[13] [0]),
    .S(rd_ptr[0]),
    .Y(_2_)
  );
  sky130_fd_sc_hd__a221oi_1 _285_ (
    .A1(\mem[14] [0]),
    .A2(_113_),
    .B1(_114_),
    .B2(\mem[15] [0]),
    .C1(_95_),
    .Y(_3_)
  );
  sky130_fd_sc_hd__o21ai_0 _286_ (
    .A1(rd_ptr[1]),
    .A2(_2_),
    .B1(_3_),
    .Y(_4_)
  );
  sky130_fd_sc_hd__mux2i_1 _287_ (
    .A0(\mem[8] [0]),
    .A1(\mem[9] [0]),
    .S(rd_ptr[0]),
    .Y(_5_)
  );
  sky130_fd_sc_hd__a221oi_1 _288_ (
    .A1(\mem[10] [0]),
    .A2(_113_),
    .B1(_114_),
    .B2(\mem[11] [0]),
    .C1(rd_ptr[2]),
    .Y(_6_)
  );
  sky130_fd_sc_hd__o21ai_0 _289_ (
    .A1(rd_ptr[1]),
    .A2(_5_),
    .B1(_6_),
    .Y(_7_)
  );
  sky130_fd_sc_hd__mux4_2 _290_ (
    .A0(\mem[0] [0]),
    .A1(\mem[1] [0]),
    .A2(\mem[2] [0]),
    .A3(\mem[3] [0]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[1]),
    .X(_8_)
  );
  sky130_fd_sc_hd__nand2_1 _291_ (
    .A(_95_),
    .B(_8_),
    .Y(_9_)
  );
  sky130_fd_sc_hd__mux4_2 _292_ (
    .A0(\mem[4] [0]),
    .A1(\mem[5] [0]),
    .A2(\mem[6] [0]),
    .A3(\mem[7] [0]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[1]),
    .X(_10_)
  );
  sky130_fd_sc_hd__nand2_1 _293_ (
    .A(rd_ptr[2]),
    .B(_10_),
    .Y(_11_)
  );
  sky130_fd_sc_hd__a21oi_1 _294_ (
    .A1(_9_),
    .A2(_11_),
    .B1(rd_ptr[3]),
    .Y(_12_)
  );
  sky130_fd_sc_hd__a31oi_1 _295_ (
    .A1(rd_ptr[3]),
    .A2(_4_),
    .A3(_7_),
    .B1(_12_),
    .Y(_13_)
  );
  sky130_fd_sc_hd__o21bai_1 _296_ (
    .A1(_109_),
    .A2(_110_),
    .B1_N(_13_),
    .Y(_14_)
  );
  sky130_fd_sc_hd__o21ai_0 _297_ (
    .A1(dout[0]),
    .A2(_107_),
    .B1(rst),
    .Y(_15_)
  );
  sky130_fd_sc_hd__a21oi_1 _298_ (
    .A1(_107_),
    .A2(_14_),
    .B1(_15_),
    .Y(_61_)
  );
  sky130_fd_sc_hd__nand2_1 _299_ (
    .A(_107_),
    .B(_114_),
    .Y(_16_)
  );
  sky130_fd_sc_hd__and3_1 _300_ (
    .A(rd_ptr[2]),
    .B(_107_),
    .C(_114_),
    .X(_17_)
  );
  sky130_fd_sc_hd__nand4_1 _301_ (
    .A(rd_ptr[2]),
    .B(rd_ptr[3]),
    .C(_107_),
    .D(_114_),
    .Y(_18_)
  );
  sky130_fd_sc_hd__o21ai_0 _302_ (
    .A1(rd_ptr[3]),
    .A2(_17_),
    .B1(rst),
    .Y(_19_)
  );
  sky130_fd_sc_hd__a21oi_1 _303_ (
    .A1(rd_ptr[3]),
    .A2(_17_),
    .B1(_19_),
    .Y(_62_)
  );
  sky130_fd_sc_hd__a21oi_1 _304_ (
    .A1(_107_),
    .A2(_114_),
    .B1(rd_ptr[2]),
    .Y(_20_)
  );
  sky130_fd_sc_hd__nor3b_1 _305_ (
    .A(_17_),
    .B(_20_),
    .C_N(rst),
    .Y(_63_)
  );
  sky130_fd_sc_hd__a21oi_1 _306_ (
    .A1(rd_ptr[0]),
    .A2(_107_),
    .B1(rd_ptr[1]),
    .Y(_21_)
  );
  sky130_fd_sc_hd__nand2_1 _307_ (
    .A(rst),
    .B(_16_),
    .Y(_22_)
  );
  sky130_fd_sc_hd__nor2_1 _308_ (
    .A(_21_),
    .B(_22_),
    .Y(_64_)
  );
  sky130_fd_sc_hd__o21ai_0 _309_ (
    .A1(rd_ptr[0]),
    .A2(_107_),
    .B1(rst),
    .Y(_23_)
  );
  sky130_fd_sc_hd__a21oi_1 _310_ (
    .A1(rd_ptr[0]),
    .A2(_107_),
    .B1(_23_),
    .Y(_65_)
  );
  sky130_fd_sc_hd__o2111ai_1 _311_ (
    .A1(_101_),
    .A2(_102_),
    .B1(wr_ptr[0]),
    .C1(wr_ptr[1]),
    .D1(wr_en),
    .Y(_24_)
  );
  sky130_fd_sc_hd__nor3_1 _312_ (
    .A(_93_),
    .B(_94_),
    .C(_24_),
    .Y(_25_)
  );
  sky130_fd_sc_hd__o21ai_0 _313_ (
    .A1(_93_),
    .A2(_24_),
    .B1(_94_),
    .Y(_26_)
  );
  sky130_fd_sc_hd__nand2_1 _314_ (
    .A(rst),
    .B(_26_),
    .Y(_27_)
  );
  sky130_fd_sc_hd__nor2_1 _315_ (
    .A(_25_),
    .B(_27_),
    .Y(_66_)
  );
  sky130_fd_sc_hd__o21ai_0 _316_ (
    .A1(_93_),
    .A2(_24_),
    .B1(rst),
    .Y(_28_)
  );
  sky130_fd_sc_hd__a21oi_1 _317_ (
    .A1(_93_),
    .A2(_24_),
    .B1(_28_),
    .Y(_67_)
  );
  sky130_fd_sc_hd__a21o_1 _318_ (
    .A1(wr_ptr[0]),
    .A2(_104_),
    .B1(wr_ptr[1]),
    .X(_29_)
  );
  sky130_fd_sc_hd__and3_1 _319_ (
    .A(rst),
    .B(_24_),
    .C(_29_),
    .X(_68_)
  );
  sky130_fd_sc_hd__o21ai_0 _320_ (
    .A1(wr_ptr[0]),
    .A2(_104_),
    .B1(rst),
    .Y(_30_)
  );
  sky130_fd_sc_hd__a21oi_1 _321_ (
    .A1(wr_ptr[0]),
    .A2(_104_),
    .B1(_30_),
    .Y(_69_)
  );
  sky130_fd_sc_hd__nand2_1 _322_ (
    .A(wr_ptr[0]),
    .B(_105_),
    .Y(_31_)
  );
  sky130_fd_sc_hd__nand3_1 _323_ (
    .A(wr_ptr[0]),
    .B(wr_ptr[1]),
    .C(_105_),
    .Y(_32_)
  );
  sky130_fd_sc_hd__nand3_1 _324_ (
    .A(_93_),
    .B(wr_ptr[3]),
    .C(_105_),
    .Y(_33_)
  );
  sky130_fd_sc_hd__nor2_1 _325_ (
    .A(_32_),
    .B(_33_),
    .Y(_70_)
  );
  sky130_fd_sc_hd__nand2_1 _326_ (
    .A(_108_),
    .B(_31_),
    .Y(_34_)
  );
  sky130_fd_sc_hd__nor2_1 _327_ (
    .A(_33_),
    .B(_34_),
    .Y(_71_)
  );
  sky130_fd_sc_hd__nand3_1 _328_ (
    .A(wr_ptr[2]),
    .B(wr_ptr[3]),
    .C(_105_),
    .Y(_35_)
  );
  sky130_fd_sc_hd__nor2_1 _329_ (
    .A(_32_),
    .B(_35_),
    .Y(_72_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _330_ (
    .A(wr_ptr[0]),
    .SLEEP(_108_),
    .X(_36_)
  );
  sky130_fd_sc_hd__nor2_1 _331_ (
    .A(_33_),
    .B(_36_),
    .Y(_73_)
  );
  sky130_fd_sc_hd__nand3_1 _332_ (
    .A(wr_ptr[2]),
    .B(_94_),
    .C(_105_),
    .Y(_37_)
  );
  sky130_fd_sc_hd__nor2_1 _333_ (
    .A(_32_),
    .B(_37_),
    .Y(_74_)
  );
  sky130_fd_sc_hd__nor2_1 _334_ (
    .A(_36_),
    .B(_37_),
    .Y(_75_)
  );
  sky130_fd_sc_hd__nand3b_1 _335_ (
    .A_N(wr_ptr[1]),
    .B(_105_),
    .C(wr_ptr[0]),
    .Y(_38_)
  );
  sky130_fd_sc_hd__nor2_1 _336_ (
    .A(_37_),
    .B(_38_),
    .Y(_76_)
  );
  sky130_fd_sc_hd__nor2_1 _337_ (
    .A(_34_),
    .B(_35_),
    .Y(_77_)
  );
  sky130_fd_sc_hd__nor2_1 _338_ (
    .A(_34_),
    .B(_37_),
    .Y(_78_)
  );
  sky130_fd_sc_hd__a21oi_1 _339_ (
    .A1(_93_),
    .A2(_94_),
    .B1(_106_),
    .Y(_39_)
  );
  sky130_fd_sc_hd__nor2_1 _340_ (
    .A(_32_),
    .B(_39_),
    .Y(_79_)
  );
  sky130_fd_sc_hd__nor2_1 _341_ (
    .A(_36_),
    .B(_39_),
    .Y(_80_)
  );
  sky130_fd_sc_hd__nor2_1 _342_ (
    .A(_33_),
    .B(_38_),
    .Y(_81_)
  );
  sky130_fd_sc_hd__nor2_1 _343_ (
    .A(_35_),
    .B(_38_),
    .Y(_82_)
  );
  sky130_fd_sc_hd__nor2_1 _344_ (
    .A(_38_),
    .B(_39_),
    .Y(_83_)
  );
  sky130_fd_sc_hd__nor2_1 _345_ (
    .A(_35_),
    .B(_36_),
    .Y(_84_)
  );
  sky130_fd_sc_hd__nor3_1 _346_ (
    .A(_106_),
    .B(_29_),
    .C(_39_),
    .Y(_85_)
  );
  sky130_fd_sc_hd__mux2i_1 _347_ (
    .A0(\mem[8] [7]),
    .A1(\mem[9] [7]),
    .S(rd_ptr[0]),
    .Y(_40_)
  );
  sky130_fd_sc_hd__a221oi_1 _348_ (
    .A1(\mem[10] [7]),
    .A2(_113_),
    .B1(_114_),
    .B2(\mem[11] [7]),
    .C1(rd_ptr[2]),
    .Y(_41_)
  );
  sky130_fd_sc_hd__o21a_1 _349_ (
    .A1(rd_ptr[1]),
    .A2(_40_),
    .B1(_41_),
    .X(_42_)
  );
  sky130_fd_sc_hd__mux2i_1 _350_ (
    .A0(\mem[12] [7]),
    .A1(\mem[13] [7]),
    .S(rd_ptr[0]),
    .Y(_43_)
  );
  sky130_fd_sc_hd__a221oi_1 _351_ (
    .A1(\mem[14] [7]),
    .A2(_113_),
    .B1(_114_),
    .B2(\mem[15] [7]),
    .C1(_95_),
    .Y(_44_)
  );
  sky130_fd_sc_hd__o21a_1 _352_ (
    .A1(rd_ptr[1]),
    .A2(_43_),
    .B1(_44_),
    .X(_45_)
  );
  sky130_fd_sc_hd__o21ai_0 _353_ (
    .A1(_42_),
    .A2(_45_),
    .B1(rd_ptr[3]),
    .Y(_46_)
  );
  sky130_fd_sc_hd__mux2i_1 _354_ (
    .A0(\mem[0] [7]),
    .A1(\mem[1] [7]),
    .S(rd_ptr[0]),
    .Y(_47_)
  );
  sky130_fd_sc_hd__a221oi_1 _355_ (
    .A1(\mem[2] [7]),
    .A2(_113_),
    .B1(_114_),
    .B2(\mem[3] [7]),
    .C1(rd_ptr[2]),
    .Y(_48_)
  );
  sky130_fd_sc_hd__o21ai_0 _356_ (
    .A1(rd_ptr[1]),
    .A2(_47_),
    .B1(_48_),
    .Y(_49_)
  );
  sky130_fd_sc_hd__mux2i_1 _357_ (
    .A0(\mem[4] [7]),
    .A1(\mem[5] [7]),
    .S(rd_ptr[0]),
    .Y(_50_)
  );
  sky130_fd_sc_hd__a221oi_1 _358_ (
    .A1(\mem[6] [7]),
    .A2(_113_),
    .B1(_114_),
    .B2(\mem[7] [7]),
    .C1(_95_),
    .Y(_51_)
  );
  sky130_fd_sc_hd__o21ai_0 _359_ (
    .A1(rd_ptr[1]),
    .A2(_50_),
    .B1(_51_),
    .Y(_52_)
  );
  sky130_fd_sc_hd__a21o_1 _360_ (
    .A1(_49_),
    .A2(_52_),
    .B1(rd_ptr[3]),
    .X(_53_)
  );
  sky130_fd_sc_hd__o211ai_1 _361_ (
    .A1(_109_),
    .A2(_110_),
    .B1(_46_),
    .C1(_53_),
    .Y(_54_)
  );
  sky130_fd_sc_hd__o21ai_0 _362_ (
    .A1(dout[7]),
    .A2(_107_),
    .B1(rst),
    .Y(_55_)
  );
  sky130_fd_sc_hd__a21oi_1 _363_ (
    .A1(_107_),
    .A2(_54_),
    .B1(_55_),
    .Y(_86_)
  );
  sky130_fd_sc_hd__xor2_1 _364_ (
    .A(wr_ptr[4]),
    .B(_25_),
    .X(_56_)
  );
  sky130_fd_sc_hd__and2_0 _365_ (
    .A(rst),
    .B(_56_),
    .X(_87_)
  );
  sky130_fd_sc_hd__and2_0 _366_ (
    .A(din[7]),
    .B(_105_),
    .X(_170_[7])
  );
  sky130_fd_sc_hd__o21ai_0 _367_ (
    .A1(_92_),
    .A2(_18_),
    .B1(rst),
    .Y(_57_)
  );
  sky130_fd_sc_hd__a21oi_1 _368_ (
    .A1(_92_),
    .A2(_18_),
    .B1(_57_),
    .Y(_89_)
  );
  sky130_fd_sc_hd__edfxtp_1 _369_ (
    .CLK(clk),
    .D(_170_[1]),
    .DE(_71_),
    .Q(\mem[8] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _370_ (
    .CLK(clk),
    .D(_170_[0]),
    .DE(_71_),
    .Q(\mem[8] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _371_ (
    .CLK(clk),
    .D(_170_[6]),
    .DE(_81_),
    .Q(\mem[9] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _372_ (
    .CLK(clk),
    .D(_170_[5]),
    .DE(_81_),
    .Q(\mem[9] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _373_ (
    .CLK(clk),
    .D(_170_[4]),
    .DE(_81_),
    .Q(\mem[9] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _374_ (
    .CLK(clk),
    .D(_170_[3]),
    .DE(_81_),
    .Q(\mem[9] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _375_ (
    .CLK(clk),
    .D(_170_[2]),
    .DE(_81_),
    .Q(\mem[9] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _376_ (
    .CLK(clk),
    .D(_170_[1]),
    .DE(_81_),
    .Q(\mem[9] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _377_ (
    .CLK(clk),
    .D(_170_[0]),
    .DE(_81_),
    .Q(\mem[9] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _378_ (
    .CLK(clk),
    .D(_170_[6]),
    .DE(_73_),
    .Q(\mem[10] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _379_ (
    .CLK(clk),
    .D(_170_[5]),
    .DE(_73_),
    .Q(\mem[10] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _380_ (
    .CLK(clk),
    .D(_170_[4]),
    .DE(_73_),
    .Q(\mem[10] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _381_ (
    .CLK(clk),
    .D(_170_[3]),
    .DE(_73_),
    .Q(\mem[10] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _382_ (
    .CLK(clk),
    .D(_170_[2]),
    .DE(_73_),
    .Q(\mem[10] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _383_ (
    .CLK(clk),
    .D(_170_[1]),
    .DE(_73_),
    .Q(\mem[10] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _384_ (
    .CLK(clk),
    .D(_170_[0]),
    .DE(_73_),
    .Q(\mem[10] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _385_ (
    .CLK(clk),
    .D(_170_[6]),
    .DE(_70_),
    .Q(\mem[11] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _386_ (
    .CLK(clk),
    .D(_170_[5]),
    .DE(_70_),
    .Q(\mem[11] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _387_ (
    .CLK(clk),
    .D(_170_[4]),
    .DE(_70_),
    .Q(\mem[11] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _388_ (
    .CLK(clk),
    .D(_170_[3]),
    .DE(_70_),
    .Q(\mem[11] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _389_ (
    .CLK(clk),
    .D(_170_[2]),
    .DE(_70_),
    .Q(\mem[11] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _390_ (
    .CLK(clk),
    .D(_170_[1]),
    .DE(_70_),
    .Q(\mem[11] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _391_ (
    .CLK(clk),
    .D(_170_[0]),
    .DE(_70_),
    .Q(\mem[11] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _392_ (
    .CLK(clk),
    .D(_170_[6]),
    .DE(_77_),
    .Q(\mem[12] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _393_ (
    .CLK(clk),
    .D(_170_[5]),
    .DE(_77_),
    .Q(\mem[12] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _394_ (
    .CLK(clk),
    .D(_170_[4]),
    .DE(_77_),
    .Q(\mem[12] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _395_ (
    .CLK(clk),
    .D(_170_[3]),
    .DE(_77_),
    .Q(\mem[12] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _396_ (
    .CLK(clk),
    .D(_170_[2]),
    .DE(_77_),
    .Q(\mem[12] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _397_ (
    .CLK(clk),
    .D(_170_[1]),
    .DE(_77_),
    .Q(\mem[12] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _398_ (
    .CLK(clk),
    .D(_170_[0]),
    .DE(_77_),
    .Q(\mem[12] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _399_ (
    .CLK(clk),
    .D(_170_[6]),
    .DE(_82_),
    .Q(\mem[13] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _400_ (
    .CLK(clk),
    .D(_170_[5]),
    .DE(_82_),
    .Q(\mem[13] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _401_ (
    .CLK(clk),
    .D(_170_[4]),
    .DE(_82_),
    .Q(\mem[13] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _402_ (
    .CLK(clk),
    .D(_170_[3]),
    .DE(_82_),
    .Q(\mem[13] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _403_ (
    .CLK(clk),
    .D(_170_[2]),
    .DE(_82_),
    .Q(\mem[13] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _404_ (
    .CLK(clk),
    .D(_170_[1]),
    .DE(_82_),
    .Q(\mem[13] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _405_ (
    .CLK(clk),
    .D(_170_[0]),
    .DE(_82_),
    .Q(\mem[13] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _406_ (
    .CLK(clk),
    .D(_170_[6]),
    .DE(_84_),
    .Q(\mem[14] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _407_ (
    .CLK(clk),
    .D(_170_[5]),
    .DE(_84_),
    .Q(\mem[14] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _408_ (
    .CLK(clk),
    .D(_170_[4]),
    .DE(_84_),
    .Q(\mem[14] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _409_ (
    .CLK(clk),
    .D(_170_[3]),
    .DE(_84_),
    .Q(\mem[14] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _410_ (
    .CLK(clk),
    .D(_170_[2]),
    .DE(_84_),
    .Q(\mem[14] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _411_ (
    .CLK(clk),
    .D(_170_[1]),
    .DE(_84_),
    .Q(\mem[14] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _412_ (
    .CLK(clk),
    .D(_170_[0]),
    .DE(_84_),
    .Q(\mem[14] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _413_ (
    .CLK(clk),
    .D(_170_[6]),
    .DE(_72_),
    .Q(\mem[15] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _414_ (
    .CLK(clk),
    .D(_170_[5]),
    .DE(_72_),
    .Q(\mem[15] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _415_ (
    .CLK(clk),
    .D(_170_[4]),
    .DE(_72_),
    .Q(\mem[15] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _416_ (
    .CLK(clk),
    .D(_170_[3]),
    .DE(_72_),
    .Q(\mem[15] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _417_ (
    .CLK(clk),
    .D(_170_[2]),
    .DE(_72_),
    .Q(\mem[15] [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _418_ (
    .CLK(clk),
    .D(_91_),
    .Q(dout[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _419_ (
    .CLK(clk),
    .D(_65_),
    .Q(rd_ptr[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _420_ (
    .CLK(clk),
    .D(_90_),
    .Q(dout[5])
  );
  sky130_fd_sc_hd__edfxtp_1 _421_ (
    .CLK(clk),
    .D(_170_[0]),
    .DE(_72_),
    .Q(\mem[15] [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _422_ (
    .CLK(clk),
    .D(_64_),
    .Q(rd_ptr[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _423_ (
    .CLK(clk),
    .D(_87_),
    .Q(wr_ptr[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _424_ (
    .CLK(clk),
    .D(_63_),
    .Q(rd_ptr[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _425_ (
    .CLK(clk),
    .D(_68_),
    .Q(wr_ptr[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _426_ (
    .CLK(clk),
    .D(_62_),
    .Q(rd_ptr[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _427_ (
    .CLK(clk),
    .D(_89_),
    .Q(rd_ptr[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _428_ (
    .CLK(clk),
    .D(_61_),
    .Q(dout[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _429_ (
    .CLK(clk),
    .D(_67_),
    .Q(wr_ptr[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _430_ (
    .CLK(clk),
    .D(_60_),
    .Q(dout[1])
  );
  sky130_fd_sc_hd__edfxtp_1 _431_ (
    .CLK(clk),
    .D(_170_[7]),
    .DE(_85_),
    .Q(\mem[0] [7])
  );
  sky130_fd_sc_hd__dfxtp_1 _432_ (
    .CLK(clk),
    .D(_59_),
    .Q(dout[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _433_ (
    .CLK(clk),
    .D(_66_),
    .Q(wr_ptr[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _434_ (
    .CLK(clk),
    .D(_58_),
    .Q(dout[3])
  );
  sky130_fd_sc_hd__edfxtp_1 _435_ (
    .CLK(clk),
    .D(_170_[7]),
    .DE(_83_),
    .Q(\mem[1] [7])
  );
  sky130_fd_sc_hd__dfxtp_1 _436_ (
    .CLK(clk),
    .D(_88_),
    .Q(dout[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _437_ (
    .CLK(clk),
    .D(_69_),
    .Q(wr_ptr[0])
  );
  sky130_fd_sc_hd__edfxtp_1 _438_ (
    .CLK(clk),
    .D(_170_[6]),
    .DE(_85_),
    .Q(\mem[0] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _439_ (
    .CLK(clk),
    .D(_170_[5]),
    .DE(_85_),
    .Q(\mem[0] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _440_ (
    .CLK(clk),
    .D(_170_[4]),
    .DE(_85_),
    .Q(\mem[0] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _441_ (
    .CLK(clk),
    .D(_170_[3]),
    .DE(_85_),
    .Q(\mem[0] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _442_ (
    .CLK(clk),
    .D(_170_[2]),
    .DE(_85_),
    .Q(\mem[0] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _443_ (
    .CLK(clk),
    .D(_170_[1]),
    .DE(_85_),
    .Q(\mem[0] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _444_ (
    .CLK(clk),
    .D(_170_[0]),
    .DE(_85_),
    .Q(\mem[0] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _445_ (
    .CLK(clk),
    .D(_170_[6]),
    .DE(_83_),
    .Q(\mem[1] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _446_ (
    .CLK(clk),
    .D(_170_[5]),
    .DE(_83_),
    .Q(\mem[1] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _447_ (
    .CLK(clk),
    .D(_170_[4]),
    .DE(_83_),
    .Q(\mem[1] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _448_ (
    .CLK(clk),
    .D(_170_[3]),
    .DE(_83_),
    .Q(\mem[1] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _449_ (
    .CLK(clk),
    .D(_170_[2]),
    .DE(_83_),
    .Q(\mem[1] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _450_ (
    .CLK(clk),
    .D(_170_[1]),
    .DE(_83_),
    .Q(\mem[1] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _451_ (
    .CLK(clk),
    .D(_170_[0]),
    .DE(_83_),
    .Q(\mem[1] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _452_ (
    .CLK(clk),
    .D(_170_[6]),
    .DE(_80_),
    .Q(\mem[2] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _453_ (
    .CLK(clk),
    .D(_170_[5]),
    .DE(_80_),
    .Q(\mem[2] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _454_ (
    .CLK(clk),
    .D(_170_[4]),
    .DE(_80_),
    .Q(\mem[2] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _455_ (
    .CLK(clk),
    .D(_170_[3]),
    .DE(_80_),
    .Q(\mem[2] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _456_ (
    .CLK(clk),
    .D(_170_[2]),
    .DE(_80_),
    .Q(\mem[2] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _457_ (
    .CLK(clk),
    .D(_170_[1]),
    .DE(_80_),
    .Q(\mem[2] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _458_ (
    .CLK(clk),
    .D(_170_[0]),
    .DE(_80_),
    .Q(\mem[2] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _459_ (
    .CLK(clk),
    .D(_170_[6]),
    .DE(_79_),
    .Q(\mem[3] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _460_ (
    .CLK(clk),
    .D(_170_[5]),
    .DE(_79_),
    .Q(\mem[3] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _461_ (
    .CLK(clk),
    .D(_170_[4]),
    .DE(_79_),
    .Q(\mem[3] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _462_ (
    .CLK(clk),
    .D(_170_[3]),
    .DE(_79_),
    .Q(\mem[3] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _463_ (
    .CLK(clk),
    .D(_170_[2]),
    .DE(_79_),
    .Q(\mem[3] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _464_ (
    .CLK(clk),
    .D(_170_[1]),
    .DE(_79_),
    .Q(\mem[3] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _465_ (
    .CLK(clk),
    .D(_170_[0]),
    .DE(_79_),
    .Q(\mem[3] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _466_ (
    .CLK(clk),
    .D(_170_[6]),
    .DE(_78_),
    .Q(\mem[4] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _467_ (
    .CLK(clk),
    .D(_170_[5]),
    .DE(_78_),
    .Q(\mem[4] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _468_ (
    .CLK(clk),
    .D(_170_[4]),
    .DE(_78_),
    .Q(\mem[4] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _469_ (
    .CLK(clk),
    .D(_170_[3]),
    .DE(_78_),
    .Q(\mem[4] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _470_ (
    .CLK(clk),
    .D(_170_[2]),
    .DE(_78_),
    .Q(\mem[4] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _471_ (
    .CLK(clk),
    .D(_170_[1]),
    .DE(_78_),
    .Q(\mem[4] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _472_ (
    .CLK(clk),
    .D(_170_[0]),
    .DE(_78_),
    .Q(\mem[4] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _473_ (
    .CLK(clk),
    .D(_170_[6]),
    .DE(_76_),
    .Q(\mem[5] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _474_ (
    .CLK(clk),
    .D(_170_[5]),
    .DE(_76_),
    .Q(\mem[5] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _475_ (
    .CLK(clk),
    .D(_170_[4]),
    .DE(_76_),
    .Q(\mem[5] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _476_ (
    .CLK(clk),
    .D(_170_[3]),
    .DE(_76_),
    .Q(\mem[5] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _477_ (
    .CLK(clk),
    .D(_170_[2]),
    .DE(_76_),
    .Q(\mem[5] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _478_ (
    .CLK(clk),
    .D(_170_[1]),
    .DE(_76_),
    .Q(\mem[5] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _479_ (
    .CLK(clk),
    .D(_170_[1]),
    .DE(_72_),
    .Q(\mem[15] [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _480_ (
    .CLK(clk),
    .D(_86_),
    .Q(dout[7])
  );
  sky130_fd_sc_hd__edfxtp_1 _481_ (
    .CLK(clk),
    .D(_170_[7]),
    .DE(_72_),
    .Q(\mem[15] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _482_ (
    .CLK(clk),
    .D(_170_[7]),
    .DE(_84_),
    .Q(\mem[14] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _483_ (
    .CLK(clk),
    .D(_170_[7]),
    .DE(_82_),
    .Q(\mem[13] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _484_ (
    .CLK(clk),
    .D(_170_[7]),
    .DE(_77_),
    .Q(\mem[12] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _485_ (
    .CLK(clk),
    .D(_170_[7]),
    .DE(_70_),
    .Q(\mem[11] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _486_ (
    .CLK(clk),
    .D(_170_[7]),
    .DE(_73_),
    .Q(\mem[10] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _487_ (
    .CLK(clk),
    .D(_170_[7]),
    .DE(_81_),
    .Q(\mem[9] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _488_ (
    .CLK(clk),
    .D(_170_[7]),
    .DE(_71_),
    .Q(\mem[8] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _489_ (
    .CLK(clk),
    .D(_170_[7]),
    .DE(_74_),
    .Q(\mem[7] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _490_ (
    .CLK(clk),
    .D(_170_[7]),
    .DE(_75_),
    .Q(\mem[6] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _491_ (
    .CLK(clk),
    .D(_170_[7]),
    .DE(_76_),
    .Q(\mem[5] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _492_ (
    .CLK(clk),
    .D(_170_[7]),
    .DE(_78_),
    .Q(\mem[4] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _493_ (
    .CLK(clk),
    .D(_170_[7]),
    .DE(_79_),
    .Q(\mem[3] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _494_ (
    .CLK(clk),
    .D(_170_[7]),
    .DE(_80_),
    .Q(\mem[2] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _495_ (
    .CLK(clk),
    .D(_170_[0]),
    .DE(_76_),
    .Q(\mem[5] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _496_ (
    .CLK(clk),
    .D(_170_[6]),
    .DE(_75_),
    .Q(\mem[6] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _497_ (
    .CLK(clk),
    .D(_170_[5]),
    .DE(_75_),
    .Q(\mem[6] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _498_ (
    .CLK(clk),
    .D(_170_[4]),
    .DE(_75_),
    .Q(\mem[6] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _499_ (
    .CLK(clk),
    .D(_170_[3]),
    .DE(_75_),
    .Q(\mem[6] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _500_ (
    .CLK(clk),
    .D(_170_[2]),
    .DE(_75_),
    .Q(\mem[6] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _501_ (
    .CLK(clk),
    .D(_170_[1]),
    .DE(_75_),
    .Q(\mem[6] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _502_ (
    .CLK(clk),
    .D(_170_[0]),
    .DE(_75_),
    .Q(\mem[6] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _503_ (
    .CLK(clk),
    .D(_170_[6]),
    .DE(_74_),
    .Q(\mem[7] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _504_ (
    .CLK(clk),
    .D(_170_[5]),
    .DE(_74_),
    .Q(\mem[7] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _505_ (
    .CLK(clk),
    .D(_170_[4]),
    .DE(_74_),
    .Q(\mem[7] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _506_ (
    .CLK(clk),
    .D(_170_[3]),
    .DE(_74_),
    .Q(\mem[7] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _507_ (
    .CLK(clk),
    .D(_170_[2]),
    .DE(_74_),
    .Q(\mem[7] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _508_ (
    .CLK(clk),
    .D(_170_[1]),
    .DE(_74_),
    .Q(\mem[7] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _509_ (
    .CLK(clk),
    .D(_170_[0]),
    .DE(_74_),
    .Q(\mem[7] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _510_ (
    .CLK(clk),
    .D(_170_[6]),
    .DE(_71_),
    .Q(\mem[8] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _511_ (
    .CLK(clk),
    .D(_170_[5]),
    .DE(_71_),
    .Q(\mem[8] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _512_ (
    .CLK(clk),
    .D(_170_[4]),
    .DE(_71_),
    .Q(\mem[8] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _513_ (
    .CLK(clk),
    .D(_170_[3]),
    .DE(_71_),
    .Q(\mem[8] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _514_ (
    .CLK(clk),
    .D(_170_[2]),
    .DE(_71_),
    .Q(\mem[8] [2])
  );
endmodule
